---
# tasks file for install_useful_tools

- name: "Add package tmux on openSUSE"
  set_fact:
    useful_tools: "{{ useful_tools }} + ['tmux']"
  when: 'ansible_os_family == "Suse" and (ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE MicroOS")'

- name: "Add package tmux on Debian"
  set_fact:
    useful_tools: "{{ useful_tools }} + ['tmux']"
  when: 'ansible_os_family == "Debian"'

- name: "Add package tmux on Fedora"
  set_fact:
    useful_tools: "{{ useful_tools }} + ['tmux']"
  when: 'ansible_distribution == "Fedora"'

- name: "Add package netcat-openbsd on *SUSE"
  set_fact:
    useful_tools: "{{ useful_tools }} + ['netcat-openbsd']"
  when: 'ansible_os_family == "Suse"'

- name: "Add package nmap-ncat on CentOS/RedHat"
  set_fact:
    useful_tools: "{{ useful_tools }} + ['nmap-ncat']"
  when: 'ansible_os_family == "RedHat"'

- name: "Install useful tools"
  package:
    name: "{{ useful_tools }}"
    state: "present"
  when: 'ansible_distribution != "openSUSE MicroOS"'

- name: "Install useful tools"
  command:
  args:
  command: '/usr/sbin/transactional-update --non-interactive pkg install {{ useful_tools | join(" ") }}'
  when: 'ansible_distribution == "openSUSE MicroOS"'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'
