---
# tasks file for install_useful_tools


#
# add emacs-nox where available
#
- name: "Add package emacs on CentOS/RedHat 7"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs'] }}"
  when:
    - 'ansible_os_family == "RedHat"'
    - 'ansible_distribution_major_version|int == 7'

- name: "Add package emacs-nox on RedHat/CentOS/RockyLinux/AlmaLinux 8 or higher"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs-nox'] }}"
  when:
    - '
      ansible_os_family == "RedHat"
      or ansible_os_family == "Rocky"
      '
    - 'ansible_distribution_major_version|int >= 8'
    - 'not ansible_pkg_mgr == "atomic_container"'

- name: "Add package emacs-nox on Debian"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs-nox'] }}"
  when:
    - 'ansible_distribution == "Debian"'

- name: "Add package emacs-nox on Fedora"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs-nox'] }}"
  when:
    - 'ansible_distribution == "Fedora"'
    - 'not ansible_pkg_mgr == "atomic_container"'

- name: "Add package emacs-nox on openSUSE"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs-nox'] }}"
  when:
    - '
      ansible_os_family == "Suse"
      or ansible_os_family == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      or ansible_os_family == "openSUSE Tumbleweed-Slowroll"
      '

- name: "Add package emacs on Ubuntu 14.04"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs'] }}"
  when:
    - 'ansible_distribution == "Ubuntu"'
    - 'ansible_distribution_major_version|int == 14'

- name: "Add package emacs-nox on Ubuntu 16.04 or later"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['emacs-nox'] }}"
  when:
    - 'ansible_distribution == "Ubuntu"'
    - 'ansible_distribution_major_version|int != 14'

#
# add tmux where available
#
- name: "Add package tmux on Alpine"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - 'ansible_os_family == "Alpine"'

- name: "Add package tmux on Debian"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - 'ansible_distribution == "Debian"'

- name: "Add package tmux on Fedora"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - 'ansible_distribution == "Fedora"'

- name: "Add package tmux on FreeBSD"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - 'ansible_os_family == "FreeBSD"'

- name: "Add package tmux on openSUSE"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - '
      ansible_os_family == "Suse"
      or ansible_os_family == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      or ansible_os_family == "openSUSE Tumbleweed-Slowroll"
      '

- name: "Add package tmux on OpenWrt"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - 'ansible_os_family == "OpenWrt"'

- name: "Add package tmux on Ubuntu"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['tmux'] }}"
  when:
    - 'ansible_distribution == "Ubuntu"'

#
# add git where available
#
- name: "Add package git on Alpine"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_os_family == "Alpine"'

- name: "Add package git on CentOS/RedHat"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_os_family == "RedHat"'

- name: "Add package git on Debian"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_distribution == "Debian"'

- name: "Add package git on Fedora"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_distribution == "Fedora"'

- name: "Add package git on FreeBSD"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_os_family == "FreeBSD"'

- name: "Add package git-core on openSUSE"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git-core'] }}"
  when:
    - '
      ansible_os_family == "Suse"
      or ansible_os_family == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      or ansible_os_family == "openSUSE Tumbleweed-Slowroll"
      '

- name: "Add package git on OpenWrt"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_os_family == "OpenWrt"'
    - 'add_git_on_openwrt | bool'

- name: "Add package git on Ubuntu"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['git'] }}"
  when:
    - 'ansible_distribution == "Ubuntu"'

#
# add netcat where available
#
- name: "Add package nmap-ncat on CentOS/RedHat"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['nmap-ncat'] }}"
  when:
    - 'ansible_os_family == "RedHat"'

- name: "Add package netcat-openbsd on Debian"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['netcat-openbsd'] }}"
  when:
    - 'ansible_distribution == "Debian"'

- name: "Add package netcat-openbsd on openSUSE"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['netcat-openbsd'] }}"
  when:
    - '
      ansible_os_family == "Suse"
      or ansible_os_family == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      '

- name: "Add package netcat-openbsd on Ubuntu"
  ansible.builtin.set_fact:
    useful_tools: "{{ useful_tools + ['netcat-openbsd'] }}"
  when:
    - 'ansible_distribution == "Ubuntu"'

#
# install the tools
#
- name: "Install useful tools without a reboot"
  ansible.builtin.package:
    name: "{{ useful_tools }}"
    state: "present"
  when:
    - 'not ansible_os_family == "openSUSE MicroOS"'
    - 'not ansible_distribution == "openSUSE MicroOS"'
    - 'not ansible_os_family == "openSUSE Leap Micro"'
    - 'not ansible_pkg_mgr == "atomic_container"'

- name: 'Install useful tools with a reboot on Fedora/RedHat CoreOS'
  community.general.rpm_ostree_pkg:
    name: "{{ useful_tools }}"
    state: 'present'
  when:
    - 'ansible_os_family == "RedHat" and ansible_pkg_mgr == "atomic_container"'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: "Install useful tools with a reboot on openSUSE MicroOS"
  ansible.builtin.package:
    name: "{{ useful_tools }}"
    state: "present"
  when:
    - '
      ansible_os_family == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      '
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Transactional-updates: force reboot at this point to not loose changes'
  ansible.builtin.meta: flush_handlers
